### ISSUE TITLE
Currently selected transcript icon is white on white background

### ISSUE THREAD

**Issue by pixelastic** [algolia/talksearch#25]
When searching inside a video (on the home page), and clicking on one of the result, the play icon becomes white. 

![2017-12-15_13h10m19](https://user-images.githubusercontent.com/283419/34041687-682797ce-e199-11e7-95b2-6a7800eae36d.gif)

I think the whole line (including icon and transcript line) should react on `:hover` to show they can be interacted with, and the currently selected one should have a more visible focus.

**Comment by Haroenv** [comment]
I can't reproduce this, is that not with the older version?

**Comment by pixelastic** [comment]
Oh, I cannot reproduce the white text/white background anymore. I guess it was a caching issue.

What about making the whole line clickable / showing that it can be interacted with?
