### ISSUE TITLE
Embedded version has double scroll bars on the demo website

### ISSUE THREAD

**Issue by pixelastic** [algolia/talksearch#27]
On https://community.algolia.com/talksearch/dotconferences.html, the website as well as the iframe both have vertical scrollbars, which makes scrolling to see results (and accessing the sidebar) confusing.

![image](https://user-images.githubusercontent.com/283419/34041945-b1e5ec48-e19a-11e7-9d53-6e93dc2fc122.png)

**Comment by Haroenv** [comment]
I'm pretty sure this isn't solvable

**Comment by pixelastic** [comment]
Maybe we can make the `height` of the `iframe`  large enough so it does not have an internal scrollbar. There might even be a way to get the inner height from inside the iframe and send it back to the parent to adapt the iframe `height` dynamically.

**Comment by Haroenv** [comment]
Should be in https://github.com/algolia/talksearch-embed/issues/15
