### ISSUE TITLE
Wrong number of results displayed when adding/removing filters

### ISSUE THREAD

**Issue by pixelastic** [algolia/talksearch#28]
This one is quite a weird bug. I don't know if it's coming from the implementation or React InstantSearch, but I managed to reproduce it several times:

![image](http://tmp.pixelastic.com/share/wrong-count.gif)
http://tmp.pixelastic.com/share/wrong-count.gif

Steps to reproduce:

- Go to https://community.algolia.com/talksearch/dotconferences.html
- Search for "security" (55 results)
- Filter on Mitchell Hashimoto (1 result)
- Search on "" (empty string) (2 results)
- Search on "agile" (0 results)
- Search on "" (empty string) (2 results)
- Unfilter on Mitchel Hasimoto (2 results displayed. should be a full page)

**Comment by Haroenv** [comment]
Superseded by https://github.com/algolia/talksearch-embed/issues/16
