### ISSUE TITLE
No transcript for TechLunch videos

### ISSUE THREAD

**Issue by pixelastic** [algolia/talksearch#29]
I checked on this one and it seems that transcripts exists, but they are not indexed: https://www.youtube.com/watch?v=o1kDVfHo8lU

![image](https://user-images.githubusercontent.com/283419/34042398-d73bfcc4-e19c-11e7-9eb7-8575b62fdc5e.png)

**Comment by Haroenv** [comment]
Can't replicate, there's transcripts for that video

**Comment by pixelastic** [comment]
Hmm ok, it's working now.

**Comment by Haroenv** [comment]
Yes, the page had the wrong index, see https://github.com/algolia/talksearch/commit/695b1541b7722931e6b32a2cea44ddbdb02f2550
