### ISSUE TITLE
Allow website owners to link to particular videos

### ISSUE THREAD

**Issue by vvo** [algolia/talksearch#6]
I believe at some point most website owners will want to link to a particular video. OR even speakers will want to share their own videos on the conference website.

To achieve this, it would require us to allow embedding the talksearch not with an `<iframe>` directly, but with a JavaScript snippet that would:
- create the iframe
- create a two way communication channel between the iframe state and the host url page
- so we can do: dotjs.com/videos?id=... and this would load the iframe with the proper video selected.

Thoughts @Haroenv and others?

**Comment by vvo** [comment]
I don't know how good it would look without using an iframe, if you provide a good looking UI then when pasted into websites it will inherit styles from the page and you might struggle afterwards giving a good experience. Still, it might work, let's do both?

I would create a JavaScript lib exposing an API like this:

```js
const talkSearchInstance = talkSearch({
  id:...,
  urlSync: ...,
  useIframe: false // by default false, can be true
});

talkSearchInstance.showVideo(); // optional, if you have urlSync you don't really need that at first, dunno
talkSearchInstance.iframe.injectStyleSheet(); // to allow customising the styling with iframe
```

You don't even need to have an iframe that is pointing to a real url, you can create an iframe from JavaScript, pointing to about:blank. And then manipulate the inside DOM to instantiate talkSearch. The lib should be responsible for that.

It would mean that by default it's not an iframe, but on some websites, you can use an iframe. Should not be that much code, it's a nice challenge also.

What do you think?

**Comment by Haroenv** [comment]
I'm not sure if I understand the issue; you can already embed single videos, as shown on the homepage. having a JS api to make the iframe is a good idea, but should be a different issue IMHO

https://community.algolia.com/talksearch/ has a single video embed

**Comment by Haroenv** [comment]
Actually I misunderstood the original question, seems doable

**Comment by Haroenv** [comment]
Superseded by https://github.com/algolia/talksearch-embed/issues/15
