### ISSUE TITLE
Scroll bars on list of tags

### ISSUE THREAD

**Issue by pixelastic** [algolia/talksearch#74]
## What
The results are displaying tags for each video, but they are all inline and requiring a scroll bar to see them all.
![image](https://user-images.githubusercontent.com/283419/35672789-de4b9498-073f-11e8-9d36-b07d2503de82.png)

## How to solve it

No-one will really scroll to see more tags, so I suggest either limiting the number of tags displayed to a fixed number, or displaying them on several lines.

**Comment by Haroenv** [comment]
I think this is fine though, horizontal scrolling exists, and there's no way to detect if the OS is one one which hides the scrollbar or show it at all times

**Comment by Haroenv** [comment]
The problem is that a few have a _lot_ of tags, and showing them all is very cluttered

**Comment by pixelastic** [comment]
Agreed that showing them all might not be very interesting. So having the user scroll to find only "non-interesting" tags is even worse :) I think we could limit the number of tags to maybe 5 or so and display them.

> there's no way to detect if the OS is one one which hides the scrollbar or show it at all times
Well, can't we configure that through `overflow-x` and `overflow-y`?

**Comment by Haroenv** [comment]
The overflow-x right now is on purpose, I wanted that interface, it looks great when scrollbars aren't so ugly

**Comment by Haroenv** [comment]
closed on https://github.com/algolia/talksearch-embed/commit/0dea72f360244cb9c3c4a908815d24cecdbc9569
